### ISSUE TITLE
I've problem open this project in browser

### ISSUE THREAD

**Issue by talehorucov** [trevsm/portfolio#1]
I installed and i'd like to run the project, but when i wrote `npm install` the project doesn't open.

code ERESOLVE
npm ERR! ERESOLVE could not resolve

While resolving: @react-three/postprocessing@1.5.1
npm ERR! Found: three@0.123.0
npm ERR! node_modules/three
npm ERR!   three@"^0.123.0" from the root project
npm ERR!   peer three@">=0.115" from @react-spring/three@9.0.0-rc.3
npm ERR!   node_modules/@react-spring/three
npm ERR!     @react-spring/three@"^9.0.0-rc.3" from the root project
npm ERR!   2 more (postprocessing, react-three-fiber)
etc.

And so many error after that. Please, could you help to fix the error.

**Comment by trevsm** [comment]
@talehorucov 

Thanks, just pushed some changes that should fix it. Use `yarn` to install and start project
